#!/bin/bash
killall -9 svxlink
sleep 3
echo "PTT1-L"; pinctrl 13 op pd dl 0
echo "PTT1-R"; pinctrl 5 op pd dl 0

/usr/local/bin/svxlink --daemon --config /usr/local/etc/svxlink/svxlink.conf --logfile /var/log/svxlink.log --runasuser=svxlink
