#!/bin/bash
read -p "Elenata PCB Version? [6-7] :" version
dd if=/dev/zero ibs=1k count=4 of=zeros.eep
case $version in
        6)
cat <<EOF>> ./eeprom_settings-v6.txt
# RFC 4122 compliant UUID
product_uuid c247d9cb-8bf6-4f12-ba9f-2823896447eb
# 16 bit product id
product_id 0x7476
# 16 bit product version
product_ver 0x0006
# ASCII vendor string  (max 255 characters)
vendor "DO7EN #6 2022/05"
# ASCII product string (max 255 characters)
product "Elenata VI pHAT Black"
# drive strength, 0=default, 1-8=2,4,6,8,10,12,14,16mA, 9-15=reserved
gpio_drive 0
# 0=default, 1=slew rate limiting, 2=no slew limiting, 3=reserved
gpio_slew 0
# 0=default, 1=hysteresis disabled, 2=hysteresis enabled, 3=reserved
gpio_hysteresis 0
# enabled on the Pi
back_power 0
setgpio  5     OUTPUT    DEFAULT
setgpio  6     INPUT     DEFAULT
setgpio  13    OUTPUT    DEFAULT
setgpio  22    OUTPUT    DEFAULT
setgpio  26    INPUT     DEFAULT
EOF
./eepmake eeprom_settings-v$version.txt eeprom_settings-v$version.eep
./eepflash.sh -y -w -f=zeros.eep -t=24c32; ./eepflash.sh -y -w -f=eeprom_settings-v$version.eep -t=24c32
;;
        7)
cat <<EOF> ./eeprom_settings-v7.txt
# RFC 4122 compliant UUID
product_uuid c247d9cb-8bf6-4f12-ba9f-2823896447eb
# 16 bit product id
product_id 0x7476
# 16 bit product version
product_ver 0x0007
# ASCII vendor string  (max 255 characters)
vendor "DO7EN #7 2022/05"
# ASCII product string (max 255 characters)
product "Elenata VII pHAT Green"
# drive strength, 0=default, 1-8=2,4,6,8,10,12,14,16mA, 9-15=reserved
gpio_drive 0
# 0=default, 1=slew rate limiting, 2=no slew limiting, 3=reserved
gpio_slew 0
# 0=default, 1=hysteresis disabled, 2=hysteresis enabled, 3=reserved
gpio_hysteresis 0
# enabled on the Pi
back_power 0
setgpio  5     OUTPUT    DEFAULT
setgpio  6     INPUT     DEFAULT
setgpio  13    OUTPUT    DEFAULT
setgpio  22    OUTPUT    DEFAULT
setgpio  26    INPUT     DEFAULT
EOF
./eepmake eeprom_settings-v$version.txt eeprom_settings-v$version.eep
./eepflash.sh -y -w -f=zeros.eep -t=24c32; ./eepflash.sh -y -w -f=eeprom_settings-v$version.eep -t=24c32
;;
        *)
                echo "Keine Zahl angegeben"
                ;;
esac
