#!/bin/bash
# DG5SSE aka DO7EN 29.09.2022
# svxlink startskript Elenata-PCB
# Wenn aplay alsamixer oder speaker-test nicht vorhanden sind, mit sudo apt-get install alsa-utils
# Aufname LineIn und Mux Regler auf LineIn setzen

gpio=$(whereis gpio | grep -i bin | cut -d" " -f2)
alsactl=$(whereis alsactl | grep -i sbin | cut -d " " -f2)
sptest=$(whereis speaker-test | grep -i bin | cut -d " " -f2)

gpioklarschiff() {
   echo "GPIO im System bekannt machen"
#PTT-R
   $gpio export 5 out
   $gpio -g write 5 0
#PTT-L
   $gpio export 13 out
   $gpio -g write 13 0
#SQL-R
   $gpio export 6 in
   $gpio -g write 6 0
#SQL-L
   $gpio export 26 in
   $gpio -g write 26 0
#LINK
   $gpio export 22 out
   $gpio -g write 22 0

   echo "Rechte setzten"
   chown -R svxlink:users /sys/class/gpio/gpio5/value
   chown -R svxlink:users /sys/class/gpio/gpio6/value
   chown -R svxlink:users /sys/class/gpio/gpio13/value
   chown -R svxlink:users /sys/class/gpio/gpio22/value
   chown -R svxlink:users /sys/class/gpio/gpio26/value

   echo "Rechte GPIO setzen"
   chmod -R 1777 /sys/class/gpio*
}

audiotest() {
   echo "Lade Alsaconfiguration"
   $alsactl restore sndrpiproto -f /home/svxlink/elenata-alsasettings.conf
   echo "gehe auf Rausche-Sendung"
   echo "PTT1-L"; $gpio -g write 13 1
   echo "PTT1-R"; $gpio -g write 5 1

# Oeffnungston 1.75kHz
   $sptest -Dplughw:sndrpiproto -c2 -l 3 -f 1750 -t sine
# Subton 110.9Hz
   $sptest -Dplughw:sndrpiproto -c2 -l 3 -f 110.9 -t sine
# Sounddatei abspielen
  if [ -f /tmp/ElenataTestaudio.wav ]
    then
         aplay /tmp/ElenataTestaudio.wav
    else
         wget https://github.com/SkyAndy/Elenata/raw/main/ElenataTestaudio.wav -O /tmp/ElenataTestaudio.wav
         aplay /tmp/ElenataTestaudio.wav
  fi

   echo "PTT1-L"; $gpio -g write 13 0
   echo "PTT1-R"; $gpio -g write 5 0

# Anpassungen speichern
   $alsactl store sndrpiproto -f /home/svxlink/elenata-alsasettings.conf
}

ptttest() {
### PTT-L Test ###
   echo "PTT1-L"; $gpio -g write 13 1
   sleep 1
   $gpio -g write 13 0
### PTT-R Test ###
   echo "PTT1-R"; $gpio -g write 5 1
   sleep 1
   $gpio -g write 5 0
### LINK Test ###
   echo "LINK"; $gpio -g write 22 1
   sleep 1
   $gpio -g write 22 0
}

start() {

   echo "Lade Audio Rec/Play Alsa-Mixer Einstellungen"
#sudo apt install alsaplayer-alsa
   $alsactl restore sndrpiproto -f /home/svxlink/elenata-alsasettings.conf

echo "Starte svxlink als Hintergrunddienst"
   /usr/bin/svxlink --daemon --config /etc/svxlink/svxlink.conf --logfile /home/svxlink/svxlink.log --runasuser=svxlink

}

stop() {
   echo "Stoppe svxlink"
   killall -9 svxlink
   # PTT abschalten
   $gpio -g write 5 0
   $gpio -g write 13 0
   sleep 2
}

gpioklarschiff

case "$1" in
   start) start;;
   stop)  stop;;
   ptttest) ptttest;;
   atest) audiotest;;
   *) echo "usage $0 start | stop | ptttest | atest" >&2
      exit 1
      ;;
esac
