#!/bin/bash
#
# DK1LO 22.03.2024
#
# svxlink startskript Elenata-PCB kernel > 6.5.4
# https://github.com/raspberrypi/linux/issues/5668
# GPIO Nummer Plus-GPIO-Chip-Nummer hier die 512
#
# Wenn aplay alsamixer oder speaker-test nicht vorhanden sind, mit sudo apt-get install alsa-utils
# Aufname LineIn und Mux Regler auf LineIn setzen
# 
gpio=$(whereis pinctrl | grep -i bin | cut -d" " -f2)
alsactl=$(whereis alsactl | grep -i sbin | cut -d " " -f2)
sptest=$(whereis speaker-test | grep -i bin | cut -d " " -f2)
echo $gpio $alsactl $sptest

#echo "13" > /sys/class/gpio/export
#echo "5" > /sys/class/gpio/export
#echo "6" > /sys/class/gpio/export
#echo "26" > /sys/class/gpio/export

echo "525" > /sys/class/gpio/export
echo "517" > /sys/class/gpio/export
echo "518" > /sys/class/gpio/export
echo "538" > /sys/class/gpio/export

gpioklarschiff() {
   echo "GPIO im System bekannt machen"
#PTT-R
   $gpio set 5 op pd dl
#PTT-L
   $gpio set 13 op pd dl
#SQL-R
   $gpio set 6 ip pd
#SQL-L
   $gpio set 26 ip pd

   echo "Rechte setzten"
   chown -R svxlink:users /sys/class/gpio/gpio517/value
   chown -R svxlink:users /sys/class/gpio/gpio518/value
   chown -R svxlink:users /sys/class/gpio/gpio525/value
   chown -R svxlink:users /sys/class/gpio/gpio538/value

   echo "Rechte GPIO setzen"
   chmod -R 1777 /sys/class/gpio*
}

audiotest() {
   echo "Lade Alsaconfiguration"
   $alsactl restore sndrpiproto -f /home/svxlink/elenata-alsasettings.conf
   echo "gehe auf Rausche-Sendung"
   echo "PTT1-L"; $gpio set 13 op pd dh
   echo "PTT1-R"; $gpio set 5 op pd dh

# Oeffnungston 1.75kHz
   $sptest -Dplughw:sndrpiproto -c2 -l 3 -f 1750 -t sine
# Subton 110.9Hz
   $sptest -Dplughw:sndrpiproto -c2 -l 3 -f 110.9 -t sine
# Sounddatei abspielen
  if [ -f /tmp/ElenataTestaudio.wav ]
    then
         aplay /tmp/ElenataTestaudio.wav
    else
         wget https://github.com/SkyAndy/Elenata/raw/main/ElenataTestaudio.wav -O /tmp/ElenataTestaudio.wav
         aplay /tmp/ElenataTestaudio.wav
  fi

   echo "PTT1-L"; $gpio set 13 op pd dl
   echo "PTT1-R"; $gpio set 5 op pd dl

# Anpassungen speichern
   $alsactl store sndrpiproto -f /home/svxlink/elenata-alsasettings.conf
}

ptttest() {
### PTT-L Test ###
   echo "PTT1-L"; $gpio set 13 op pd dh
   sleep 1
   $gpio set 13 op pd dl
### PTT-R Test ###
   echo "PTT1-R"; $gpio set 5 op pd dh
   sleep 1
   $gpio set 5 op pd dl
}

start() {

   echo "Lade Audio Rec/Play Alsa-Mixer Einstellungen"
#sudo apt install alsaplayer-alsa
   $alsactl restore sndrpiproto -f /home/svxlink/elenata-alsasettings.conf

echo "Starte svxlink als Hintergrunddienst"
   /usr/local/bin/svxlink --daemon --config /usr/local/etc/svxlink/svxlink.conf --logfile /tmp/svxlink.log --runasuser=svxlink

}

stop() {
   echo "Stoppe svxlink"
   killall -9 svxlink
   # PTT abschalten
   $gpio set 5 op pd dl
   $gpio set 13 op pd dl
   sleep 2
}

gpioklarschiff

case "$1" in
   start) start;;
   stop)  stop;;
   ptttest) ptttest;;
   atest) audiotest;;
   *) echo "usage $0 start | stop | ptttest | atest" >&2
      exit 1
      ;;
esac
